repos:
# general house-keeping tasks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-symlinks
# formatting tasks
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.6
    hooks:
    -   id: clang-format
        types_or: [c++, c, c#, cuda, java, javascript, json, objective-c, proto, textproto]
        args: ["-style=llvm"]
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
    -   id: black
